
// This file was automatically generated by @bearstudio/astro-typed-routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from '@bearstudio/astro-typed-routes';

const ROUTES_CONFIG = {
  "en": {
    "contact": {
      "application-process-bearstudio": {}
    },
    "legal-notice": {},
    "services": {
      "ux-design": {}
    },
    "team": {
      ":id": {}
    }
  },
  "fr": {
    "blog": {
      ":page": {},
      "auteurs": {
        ":author": {
          ":page": {}
        }
      },
      "posts": {
        ":id": {}
      }
    },
    "contact": {
      "processus-candidature-bearstudio": {}
    },
    "equipe": {
      ":id": {}
    },
    "mentions-legales": {},
    "prestations": {
      "ux-design": {}
    }
  },
  "rss.xml": {},
  "styleguide": {}
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
