// This file was automatically generated by @bearstudio/astro-typed-routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from '@bearstudio/astro-typed-routes';

const ROUTES_CONFIG = {
  en: {
    contact: {},
    services: {
      'ux-design': {},
    },
    team: {
      ':id': {},
    },
  },
  fr: {
    blog: {
      ':page': {},
      posts: {
        ':id': {},
      },
    },
    contact: {},
    equipe: {
      ':id': {},
    },
    prestations: {
      'ux-design': {},
    },
  },
  'rss.xml': {},
  styleguide: {},
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
